### ISSUE TITLE
Vim port

### ISSUE THREAD

**Issue by epszaw** [uloco/theme-bluloco-light#13]
Hello! Thank you for awesome theme :)
Is it here any possibility to port light version to vim?

**Comment by uloco** [comment]
I don't know of any fast way to port this theme to vim.
I already tried porting it, but the problem is, that the color highlighting in vim is highly dependant on the plugins you use for the languages. I think the main philosophy of this theme really shines, just because I took a lot of time and effort to optimize the colors for different languages by hand. This needs to be done for vim and the corresponding language plugins too then.

I will start documenting the key philosophy behind this theme, the colors, why and where I used them. Perhaps afterwards we can start porting this to vim together?

**Comment by lamartire** [comment]
I think yes, no problem :)

**Comment by uloco** [comment]
@epszaw I know it's been quite some time, but If you are still intreseted in this and are using neovim, have a look here: https://github.com/uloco/bluloco.nvim

**Comment by epszaw** [comment]
Such a great news here! :)
