### ISSUE TITLE
How to customize some of the colors?

### ISSUE THREAD

**Issue by DEKOHG** [uloco/theme-bluloco-light#54]
Hi,
Thanks for providing a nice color theme, but I want to change some of the color from what you provided. How can I do that? Thank you.

**Comment by uloco** [comment]
Do you want to change workspace or syntax colors?
For workspace it is described here: https://code.visualstudio.com/api/references/theme-color
Just put it in your settings.json

If you tell me what exactly you want to change, I may be able to help you more specifically.

**Comment by DEKOHG** [comment]
I want to change some of the colors described in the Syntax Palette at https://github.com/uloco/theme-bluloco-light and the curso color to my preferred ones, but I'm not show where to edit them.

**Comment by uloco** [comment]
The cursor is pretty easy to do (replace Bluloco Light with _Bluloco Light Italic_ if you are using this instead:

```
  "workbench.colorCustomizations": {
    "[Bluloco Light]": {
      "editorCursor.foreground": "#0000ff"
    }
  },
```

The syntax colors are a bit tricky because you will have to edit tokenColors and semanticColors to fix it properly.
Those settings are `editor.tokenColorCustomizations` and `editor.semanticTokenColorCustomizations.
You have to use the textmate setting and copy the values from the source file here (the theme json file) to make it work.
