### ISSUE TITLE
Python's IN function not formatted correctly?

### ISSUE THREAD

**Issue by br4n5** [uloco/theme-bluloco-light#58]
There is a inconsistency on how ‘IN’ is formatted in the Python’s IF and FOR functions.
While the ‘IN’ in IF is, say, correctly formatted the same does not happen in the ‘IN’ in IF function.
The cobalt I use apparently works correctly:
You can check a comparison of the screenshots I have done:
https://imgur.com/ra1vicl
https://imgur.com/zHFm2tl
https://imgur.com/GkNk6At

**Comment by uloco** [comment]
Hi, thanks for reporting / requesting.

This is because the `in` is recognized as a control flow keyword (like for, if etc.) and as an operator in the second case.
So are the other keyword operators `and` `is` `or` and `not` that have the same color (purpleish)

From my perspective this is by design, since operators (like &&, || etc.) are always this color.
Otherwise it is also a keyword and would make sense to make it blue.

When I change this, it will also change how `and` `or`, etc. is rendered.
Is this what you want?

**Comment by br4n5** [comment]
Hi Mr, thank you for sparing some time to write back.

I was asking out of curiosity since I have just started studying python and spotted this “issue”.

So I am not sure how it effectively affects people’s coding.

Your theme rocks, by the way.

Wish you and your family nothing but the best of luck!
________________________________

**Comment by uloco** [comment]
Thanks, glad you like it :)

Well you are right, it does make sense to change something here, but I guess I should update the places where I changed the keyword operators to blue. So it is the other way round.

Operators in this purpleish color are normally special characters (like &, |, etc.), but all word based operators should also look purple since this is more consistent.

I wish you also good luck and success with your studies.

**Comment by uloco** [comment]
I guess I like how it is at the moment. sorry will not change. if it bugs you, you can override in your settings like so
```
  "editor.tokenColorCustomizations": {
    "[Bluloco Light]": {
      "textMateRules": [
        {
          "scope": "keyword.operator.logical.python",
          "settings": {
            "foreground": "#0098DD"
          }
        }
      ]
    }
  },
```
